"""Pydantic request/response schemas for the workflow API (SRP: data shapes only)."""
from pydantic import BaseModel, Field


class TicketRequest(BaseModel):
    """Payload accepted by POST /run and POST /run/stream."""

    ticket_text: str = Field(
        ...,
        min_length=1,
        description="The development ticket text that drives the whole workflow.",
        examples=["Add a /metrics endpoint that exposes Prometheus counters."],
    )


class RunResponse(BaseModel):
    """Final aggregated state returned by POST /run."""

    spec: str = Field(description="Technical specification generated by the Spec Agent.")
    spec_feedback: str = Field(description="Last feedback from the Validator Agent.")
    test_output: str = Field(description="Raw stdout/stderr from the Docker pytest run.")
    tests_passed: bool = Field(description="Whether all tests passed.")
    pr_url: str = Field(description="URL of the opened GitHub Pull Request.")
    iteration_count: int = Field(description="Total coding iteration cycles executed.")
    intent: str = Field(description="Detected intent of the user request.")
    answer: str = Field(description="Direct answer if the intent was a QUESTION.")
