from typing import Any, TypedDict

AgentReport = dict[str, Any]

class GraphState(TypedDict):
    # ── LLM / Logging / execution metadata ──────────────────────────────────────────────
    log_file_path:      str      # Absolute path to the request log file
    chat_log_file_path: str      # Absolute path to the chat log file
    total_tokens:       int      # Cumulative token count for this request
    iteration_count:    int      # Number of coding iterations attempted

    # ── Ticket / Issue ──────────────────────────────────────────────────────
    ticket_text:        str      # Issue body used as the coding brief
    spec:               str      # Technical specification generated by Spec Agent
    issue_number:       int      # GitHub issue number (0 if manual run)
    branch_name:        str      # Git branch created for the fix
    repo_url:           str      # HTTPS clone URL of the target repo

    # ── Agent communication ───────────────────────────────────────────────────
    agent_reports:      list[AgentReport]   # append-only log of all reports
    orchestrator_inbox: AgentReport         # the *latest* report the orchestrator is acting on

    # ── Language detection (language-agnostic pipeline) ─────────────────────
    detected_language:  str      # Primary language detected in workspace (e.g. "Java", "Python")
    detected_framework: str      # Framework detected in workspace   (e.g. "Spring Boot", "Django")

    # ── Spec loop ───────────────────────────────────────────────────────────
    spec:               str      # Technical specification generated by Spec Agent

    # ── Per-agent outputs ─────────────────────────────────────────────────────
    test_output:        str      # Raw test runner stdout/stderr from Docker sandbox
    tests_passed:       bool     # Whether the last test run passed
    tests_generated:    bool     # Whether the Testing Agent has generated tests
    agent_outcome:      str      # "success" | "failed"

    # ── Orchestration ───────────────────────────────────────────────────────
    intent:             str      # Detected intent: "QUESTION", "CODING_WITH_SPEC", "STANDARD_FLOW", "VALIDATE_MR"
    answer:             str      # Direct answer for "QUESTION" intent
    pipeline:           list[str]  # Dynamic list of agents to execute
    pipeline_step:      int      # Track current step in pipeline
    next_node:          str      # authoritative "go here next" set by orchestrator

    # ── PR ──────────────────────────────────────────────────────────────────
    pr_url:             str      # URL of the opened GitHub Pull Request

    # ── Model profile ───────────────────────────────────────────────────────
    model_profile:      str      # "LOW" | "STANDARD" | "HIGH"
    max_tool_out:       int      # Maximum number of tool calls allowed

    # ── MCP ─────────────────────────────────────────────────────────────────
    mcp_servers:        list[dict] # List of MCP server configurations

    # ── LangGraph message list ────────────────────────────────────────────────
    messages:           list[Any]  # List of LangGraph messages
